output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.private_eks.cluster_endpoint
}

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.private_eks.cluster_id
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.private_eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.private_eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.private_eks.config_map_aws_auth
}

output "cluster_name" {
  description = "AWS EKS cluster."
  value       = var.cluster_name
}

output "node_groups" {
  description = "Outputs from node groups"
  value       = module.private_eks.node_groups
}

output "cluster_security_group" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.private_eks.cluster_security_group_id
}
